### PR TITLE
Added several GraphQL tools, GraphQL security academy and API checklist

### PR DESCRIPTION
**Pull request by AlexandraC0**
Added several GraphQL tools (Goctopus, GraphQL armor), GraphQL wordlist, API Security Academy (focused on GraphQL) and API security checklist

### CODE REVIEW

**Comment by arainho** [comment]
> Added several GraphQL tools (Goctopus, GraphQL armor), GraphQL wordlist, API Security Academy (focused on GraphQL) and API security checklist

Hello @AlexandraC0, can you please fix the requested changes ?
So that we can solve the "Pending" ones; and I can merge your PR.

**Comment by AlexandraC0** [comment]
Hello @arainho I've applied the fix on the 2nd on November (see Commit on Nov 2, 2023) once I saw it was needed. So far, there are no conflicts that I can see on my side. Is everything ok for you?

**Comment by arainho** [comment]
Hello @AlexandraC0,

There are no conflicts; can you please make these two changes ?

1. The [API Security Checklist](https://escape.tech/blog/api-security-checklist) from Escape is directly advertising a company product; so it does not fit in the repository [+contributions](https://github.com/arainho/awesome-api-security#contributions) purposes.  
For the PR to be accepted; this line (86) needs to be removed, sorry.

2. You have an entry for graphql-armor pointing to goctopus; if you can correct the url I appreciate it.

**Comment by arainho** [comment]
@AlexandraC0

Just remove the line 86 (referred in point 1) from `Escape-Technologies:master` branch; so I can merge the PR.
Point 2 I can fix afterwords, if you prefer.

**Comment by AlexandraC0** [comment]
@arainho should be ok now! I've done both

**Pull request merged**
